<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OriginSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $city_province = [
            ['id' => 1, 'city_province' => 'Banda Aceh, Aceh'],
            ['id' => 2, 'city_province' => 'Langsa, Aceh'],
            ['id' => 3, 'city_province' => 'Lhokseumawe, Aceh'],
            ['id' => 4, 'city_province' => 'Sabang, Aceh'],
            ['id' => 5, 'city_province' => 'Subulussalam, Aceh'],
            ['id' => 6, 'city_province' => 'Denpasar, Bali'],
            ['id' => 7, 'city_province' => 'Pangkal Pinang, Bangka Belitung'],
            ['id' => 8, 'city_province' => 'Cilegon, Banten'],
            ['id' => 9, 'city_province' => 'Serang, Banten'],
            ['id' => 10, 'city_province' => 'Tangerang, Banten'],
            ['id' => 11, 'city_province' => 'Tangerang Selatan, Banten'],
            ['id' => 12, 'city_province' => 'Bengkulu, Bengkulu'],
            ['id' => 13, 'city_province' => 'Yogyakarta, DI Yogyakarta'],
            ['id' => 14, 'city_province' => 'Jakarta, DKI Jakarta'],
            ['id' => 15, 'city_province' => 'Gorontalo, Gorontalo'],
            ['id' => 16, 'city_province' => 'Banjar, Jawa Barat'],
            ['id' => 17, 'city_province' => 'Bandung, Jawa Barat'],
            ['id' => 18, 'city_province' => 'Bekasi, Jawa Barat'],
            ['id' => 19, 'city_province' => 'Bogor, Jawa Barat'],
            ['id' => 20, 'city_province' => 'Cimahi, Jawa Barat'],
            ['id' => 21, 'city_province' => 'Cirebon, Jawa Barat'],
            ['id' => 22, 'city_province' => 'Depok, Jawa Barat'],
            ['id' => 23, 'city_province' => 'Sukabumi, Jawa Barat'],
            ['id' => 24, 'city_province' => 'Tasikmalaya, Jawa Barat'],
            ['id' => 25, 'city_province' => 'Magelang, Jawa Tengah'],
            ['id' => 26, 'city_province' => 'Pekalongan, Jawa Tengah'],
            ['id' => 27, 'city_province' => 'Salatiga, Jawa Tengah'],
            ['id' => 28, 'city_province' => 'Semarang, Jawa Tengah'],
            ['id' => 29, 'city_province' => 'Surakarta, Jawa Tengah'],
            ['id' => 30, 'city_province' => 'Tegal, Jawa Tengah'],
            ['id' => 31, 'city_province' => 'Batu, Jawa Timur'],
            ['id' => 32, 'city_province' => 'Blitar, Jawa Timur'],
            ['id' => 33, 'city_province' => 'Kediri, Jawa Timur'],
            ['id' => 34, 'city_province' => 'Madiun, Jawa Timur'],
            ['id' => 35, 'city_province' => 'Malang, Jawa Timur'],
            ['id' => 36, 'city_province' => 'Mojokerto, Jawa Timur'],
            ['id' => 37, 'city_province' => 'Pasuruan, Jawa Timur'],
            ['id' => 38, 'city_province' => 'Probolinggo, Jawa Timur'],
            ['id' => 39, 'city_province' => 'Surabaya, Jawa Timur'],
            ['id' => 40, 'city_province' => 'Jambi, Jambi'],
            ['id' => 41, 'city_province' => 'Sungai Penuh, Jambi'],
            ['id' => 42, 'city_province' => 'Pontianak, Kalimantan Barat'],
            ['id' => 43, 'city_province' => 'Singkawang, Kalimantan Barat'],
            ['id' => 44, 'city_province' => 'Banjarbaru, Kalimantan Selatan'],
            ['id' => 45, 'city_province' => 'Banjarmasin, Kalimantan Selatan'],
            ['id' => 46, 'city_province' => 'Palangkaraya, Kalimantan Tengah'],
            ['id' => 47, 'city_province' => 'Balikpapan, Kalimantan Timur'],
            ['id' => 48, 'city_province' => 'Bontang, Kalimantan Timur'],
            ['id' => 49, 'city_province' => 'Samarinda, Kalimantan Timur'],
            ['id' => 50, 'city_province' => 'Tarakan, Kalimantan Utara'],
            ['id' => 51, 'city_province' => 'Batam, Kepulauan Riau'],
            ['id' => 52, 'city_province' => 'Tanjung Pinang, Kepulauan Riau'],
            ['id' => 53, 'city_province' => 'Bandar Lampung, Lampung'],
            ['id' => 54, 'city_province' => 'Metro, Lampung'],
            ['id' => 55, 'city_province' => 'Ambon, Maluku'],
            ['id' => 56, 'city_province' => 'Ternate, Maluku Utara'],
            ['id' => 57, 'city_province' => 'Tidore Kepulauan, Maluku Utara'],
            ['id' => 58, 'city_province' => 'Bima, Nusa Tenggara Barat'],
            ['id' => 59, 'city_province' => 'Mataram, Nusa Tenggara Barat'],
            ['id' => 60, 'city_province' => 'Kupang, Nusa Tenggara Timur'],
            ['id' => 61, 'city_province' => 'Manokwari, Papua Barat'],
            ['id' => 62, 'city_province' => 'Sorong, Papua Barat Daya'],
            ['id' => 63, 'city_province' => 'Jayapura, Papua'],
            ['id' => 64, 'city_province' => 'Jayawijaya, Papua Pegunungan'],
            ['id' => 65, 'city_province' => 'Nabire, Papua Tengah'],
            ['id' => 66, 'city_province' => 'Merauke, Papua Selatan'],
            ['id' => 67, 'city_province' => 'Dumai, Riau'],
            ['id' => 68, 'city_province' => 'Pekanbaru, Riau'],
            ['id' => 69, 'city_province' => 'Mamuju, Sulawesi Barat'],
            ['id' => 70, 'city_province' => 'Palu, Sulawesi Tengah'],
            ['id' => 71, 'city_province' => 'Baubau, Sulawesi Tenggara'],
            ['id' => 72, 'city_province' => 'Kendari, Sulawesi Tenggara'],
            ['id' => 73, 'city_province' => 'Makassar, Sulawesi Selatan'],
            ['id' => 74, 'city_province' => 'Palopo, Sulawesi Selatan'],
            ['id' => 75, 'city_province' => 'Parepare, Sulawesi Selatan'],
            ['id' => 76, 'city_province' => 'Bitung, Sulawesi Utara'],
            ['id' => 77, 'city_province' => 'Kotamobagu, Sulawesi Utara'],
            ['id' => 78, 'city_province' => 'Manado, Sulawesi Utara'],
            ['id' => 79, 'city_province' => 'Tomohon, Sulawesi Utara'],
            ['id' => 80, 'city_province' => 'Bukittinggi, Sumatera Barat'],
            ['id' => 81, 'city_province' => 'Padang, Sumatera Barat'],
            ['id' => 82, 'city_province' => 'Padang Panjang, Sumatera Barat'],
            ['id' => 83, 'city_province' => 'Pariaman, Sumatera Barat'],
            ['id' => 84, 'city_province' => 'Payakumbuh, Sumatera Barat'],
            ['id' => 85, 'city_province' => 'Sawahlunto, Sumatera Barat'],
            ['id' => 86, 'city_province' => 'Solok, Sumatera Barat'],
            ['id' => 87, 'city_province' => 'Lubuklinggau, Sumatera Selatan'],
            ['id' => 88, 'city_province' => 'Pagar Alam, Sumatera Selatan'],
            ['id' => 89, 'city_province' => 'Palembang, Sumatera Selatan'],
            ['id' => 90, 'city_province' => 'Prabumulih, Sumatera Selatan'],
            ['id' => 91, 'city_province' => 'Binjai, Sumatera Utara'],
            ['id' => 92, 'city_province' => 'Gunungsitoli, Sumatera Utara'],
            ['id' => 93, 'city_province' => 'Medan, Sumatera Utara'],
            ['id' => 94, 'city_province' => 'Padangsidempuan, Sumatera Utara'],
            ['id' => 95, 'city_province' => 'Pematangsiantar, Sumatera Utara'],
            ['id' => 96, 'city_province' => 'Sibolga, Sumatera Utara'],
            ['id' => 97, 'city_province' => 'Tanjungbalai, Sumatera Utara'],
            ['id' => 98, 'city_province' => 'Tebing Tinggi, Sumatera Utara'],
        ];

        DB::table('origin')->insert($city_province);
    }
}
