version: '3.8'

services:
  # Laravel API Application
  app:
    image: syachint/cuanki-api:latest
    container_name: cuanki-api
    restart: unless-stopped
    working_dir: /var/www/public
    volumes:
      - ./var/www/public
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    environment:
      - APP_NAME=CUANKI
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - APP_URL=${APP_URL}
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=database
      - SESSION_DRIVER=file
    depends_on:
      - postgres
    networks:
      - cuanki-network

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: cuanki-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - cuanki-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: cuanki-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cuanki-network

volumes:
  postgres_data:
    driver: local

networks:
  cuanki-network:
    driver: bridge
